# The Terraform configuration in this project provisions the following AWS resources using the AWS Elastic Beanstalk service:
# - Creates an Elastic Beanstalk application named "2048-Game" with a description.
# - Defines an IAM role named "elastic_beanstalk_instance_role" that allows EC2 instances to assume the role.
# - Creates an IAM instance profile named "elastic_beanstalk_instance_profile" associated with the instance role.
# - Sets up an Elastic Beanstalk environment named "2048-Game-Environment" for hosting the game.
# - Specifies the solution stack as "64bit Amazon Linux 2 v3.5.9 running Docker".
# - Configures the environment with a "WebServer" tier, a "t2.micro" instance type, and a load-balanced environment type.
# - Associates the IAM instance profile with the environment for proper permissions.
# - Adds tags for easy identification of the resources.

name: Deploy to AWS Elastic Beanstalk using Terraform

on:
  push:
    branches:
      - main

jobs:
  setup_build_deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Plan Terraform
      run: terraform plan

    - name: Apply Terraform
      run: terraform apply -auto-approve

    - name: Create deployment package
      run: zip -r application.zip .

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: 2048-Game
        environment_name: 2048-Game-Environment
        version_label: ${{ github.sha }}
        region: us-east-1
        deployment_package: application.zip
        wait_for_environment_recovery: 300